parameters:
    sidus_data_grid.model.datagrid.class: Sidus\DataGridBundle\Model\DataGrid
    sidus_data_grid.datagrid_configuration.handler.class: Sidus\DataGridBundle\Configuration\DataGridConfigurationHandler
    sidus_data_grid.renderer.twig.class: Sidus\DataGridBundle\Templating\TwigRenderer
    sidus_data_grid.form.link.type.class: Sidus\DataGridBundle\Form\Type\LinkType

services:
    sidus_data_grid.datagrid_configuration.handler:
        class: %sidus_data_grid.datagrid_configuration.handler.class%

    sidus_data_grid.renderer.twig:
        class: %sidus_data_grid.renderer.twig.class%
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    sidus_data_grid.form.link.type:
        class: %sidus_data_grid.form.link.type.class%
        tags:
            - { name: form.type, alias: sidus_link }
