parameters:
    sidus_data_grid.model.datagrid.class: Sidus\DataGridBundle\Model\DataGrid

services:
    sidus_data_grid.datagrid_configuration.handler:
        class: Sidus\DataGridBundle\Configuration\DataGridConfigurationHandler

    sidus_data_grid.renderer.twig:
        class: Sidus\DataGridBundle\Templating\TwigRenderer
        arguments: ['@translator', '@property_accessor']
        tags:
            - { name: twig.extension }

    sidus_data_grid.form.link.type:
        class: Sidus\DataGridBundle\Form\Type\LinkType
        tags:
            - { name: form.type }
