services:
    sidus_data_grid.renderer:
        class: Sidus\DataGridBundle\Renderer\GenericRenderer
        arguments:
            - '@translator'
            - '@property_accessor'

    sidus_data_grid.column_renderer:
        class: Sidus\DataGridBundle\Renderer\DefaultColumnRenderer
        arguments:
            - '@translator'
