services:
    Sidus\DataGridBundle\Renderer\RenderableInterface:
        alias: Sidus\DataGridBundle\Renderer\GenericRenderer

    Sidus\DataGridBundle\Renderer\GenericRenderer:
        autowire: true
        public: false

    Sidus\DataGridBundle\Renderer\ColumnRendererInterface:
        alias: Sidus\DataGridBundle\Renderer\DefaultColumnRenderer

    Sidus\DataGridBundle\Renderer\DefaultColumnRenderer:
        autowire: true
        public: false
